/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crio_projects;
import java.net.MalformedURLException;

// import main.java.crio_projects.bookmyshow;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        // TestCases tests = new TestCases(); // Initialize your test class

        // searchamazon sa = new searchamazon();

        // bookmyshow bms = new bookmyshow();
        // linkedinpost link = new linkedinpost();
        // imageurls im = new imageurls();
        // nested_frames nf = new nested_frames();
        // imdbratings imdb_rat = new imdbratings();
        windowhandle win = new windowhandle();
        //TODO: call your test case functions one after other here

        // sa.searchamazon();
        // tests.testCase01();
        // bms.bookmyshow();
        // link.linkedinpost();
        // im.imageurls();
        // nf.nested_frames();
        // imdb_rat.imdbratings();
        win.windowhandle();
        //END Tests
        // bms.endTest();
        // link.endtest();
        // sa.endTest();
        // im.endTest();
        // nf.endTest();
        // imdb_rat.endTest();
        win.endTest();
        // tests.endTest(); // End your test by clearning connections and closing browser
    }
    
    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}